services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: tools_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
      
  # server:
  #   build:
  #     context: ./server/
  #     dockerfile: Dockerfile
  #   container_name: spring_app
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-network
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tools_db
  #     SPRING_DATASOURCE_USERNAME: admin
  #     SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge