server:
  port: 8080

spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/tools_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
app:
  jwt:
    secret: mySecretKey123456789012345678901234567890
    expiration-ms: 86400000
