package com.toolsai.server.model.enums;

public enum NotificationType {
    MODEL_LIKED,
    MODEL_COMMENTED,
    MODEL_RATED,
    MODEL_APPROVED,
    MODEL_REJECTED,
    ORGANIZATION_FOLLOWED,
    SYSTEM_ANNOUNCEMENT,
    SECURITY_ALERT,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SUBSCRIPTION_EXPIRED,
    ACCOUNT_VERIFIED,
    PASSWORD_CHANGED,
    NEW_FOLLOWER,
    COMMENT_REPLY,
    MENTION,
    WEEKLY_DIGEST,
    MONTHLY_REPORT
}